# Add GH action workflow for Slack integration for workflows, jobs and steps
# https://github.com/act10ns/slack
name: Slack GH action notifier

on:
  workflow_call:
    inputs:
      message:
        required: true
        type: string
    secrets:
      SLACK_WEBHOOK_URL:
        description: "slack webhook URL to publish notifications"
        required: true

jobs:
  slack:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    steps:
      - uses: act10ns/slack@v2
        with:
          status: starting
          channel: '#git-e2e-tests'
          message: ${{ inputs.message }}
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
