name: Playwright Tests

on:
  push:
    branches: [ main, master ]

  pull_request:
    branches: [ main, master ]


jobs:
  # notify:
  #   # run slack-notifier workflow
  #   uses: ./.github/workflows/call-slack-notifier.yml
  #   with:
  #     message: Starting push to main branch playwright tests run...
  #   secrets:
  #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  test:
    uses: ./.github/workflows/call-run-tests.yml

  publish_report:
    # using always() is not ideal here, because it would also run if the workflow was cancelled
    if: "success() || needs.test.result == 'failure'"
    needs: [test]
    uses: ./.github/workflows/call-publish-report.yml
    # runs-on: ubuntu-latest
    # 
    # 
    # continue-on-error: true
    # steps:
    #   - name: Publish test runtime report
        # uses: ./.github/workflows/call-publish-report.yml
