# This is a basic workflow that is manually triggered

name: Manual workflow - just for testing

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        description: 'Manual workflow trigger'

jobs:
  test:
    name: Run tests
    uses: ./.github/workflows/call-run-tests.yml
