name: Playwright Tests

on:
  push:
    branches: [ main, master ]

  pull_request:
    branches: [ main, master ]


jobs:
  # notify:
  #   # run slack-notifier workflow
  #   uses: ./.github/workflows/call-slack-notifier.yml
  #   with:
  #     message: Starting push to main branch playwright tests run...
  #   secrets:
  #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  test_and_publish:
    name: Run tests and publish report
    runs-on: ubuntu-latest
    steps:
      - name: check out branch
        uses: actions/checkout@v3

      - name: run tests
        uses: ./.github/workflows/run-tests

      - name: publish report
        uses: ./.github/workflows/publish-report

  # publish_report:
    # # using always() is not ideal here, because it would also run if the workflow was cancelled
    # if: "success() || needs.test.result == 'failure'"
    # needs: [test]
    # continue-on-error: true
    # uses: ./.github/workflows/call-publish-report.yml
